### ISSUE TITLE
Workshop Checklist Oct 2021

### ISSUE THREAD

**Issue by rosemm** [skadauke/intro-to-r-for-clinicians-chop#26]
**>1 Week pre-course**

- [ ]  Recruit TAs
- [ ]  Set dates and calendar holds for:
     - [ ]  Helper onboarding
     - [ ]  Pre-course tech check
     - [ ]  Post-course Intro CHOP R session
- [ ]  Course sign ups and outreach

**<1 Week pre-course**

- [ ]  Update slides and exercises
- [ ]  Create course pack
- [ ]  Update website
- [ ]  Send welcome email and calendar holds (pre-course tech check, course, post-course CHOPR meeting)
- [ ]  Set up training environment and backup
     - [ ]  Resize training environment before and after pre-workshop tech check
     - [ ]  Resize training environment before the workshop
- [ ]  Set up Zoom rooms for tech check and main session
- [ ]  Course project sign-up form
- [ ]  Final pre-workshop reminder email with: start time, Zoom link, link to pre-course survey, link to course website, Excel sheet with usernames, course pack.

**Post-course**

- [ ]  Send thank-you email with: post-course survey, mini project sign up link, CHOPR user group sign up link, link to website
- [ ]  Recording
     - [ ]  Upload to YouTube
     - [ ]  Add link to website
     - [ ]  Let participants know
- [ ]  Send welcome email to course project participants, Rmd template, and Doodle for course project kick-off session
- [ ]  Postmortem
     - [ ]  Evaluate feedback forms
     - [ ]  Write post-mortem notes
     - [ ]  Have postmortem session
- [ ]  Send books
- [ ]  Plan next iteration
